---
abstract: 'Format checklists'
author:
  - 'Mathias Weidner <mamawe@cpan.org>'
build_requires:
  File::Spec: 0
  Probe::Perl: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Checklist-Formatter
provides:
  App::Checklist::Formatter:
    file: lib/App/Checklist/Formatter.pm
    version: v0.1.0
requires:
  Carp: 0
  perl: v5.6.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.5
